# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-02 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_remove_location_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
