# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('pokersessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokersessionupdate',
            name='game',
        ),
        migrations.AddField(
            model_name='pokersession',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
            preserve_default=False,
        ),
    ]
