# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokersessions', '0002_auto_20161214_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokersessionupdate',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
