# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokersessions', '0003_pokersessionupdate_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokersessionupdate',
            name='buy_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='pokersessionupdate',
            name='chip_stack',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
