# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokersessions', '0005_pokersession_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokersession',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokersessionupdate',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
